import { SidebarState } from "../../state.slint";
import { IconDisplay, IconSet } from "@lucide";

export component ModsButton {
    width: 100%;

    VerticalLayout {
        alignment: start;
        padding: SidebarState.is_open ? 15px : 11px;
        padding-top: 5px;
        animate padding {
            duration: 200ms;
            easing: ease-in-out;
        }
        Rectangle {
            padding: SidebarState.is_open ? 3px : 4px;
            background: touch-area.has-hover ? #2e2e2eaa : transparent;
            animate background {
                duration: 100ms;
            }
            touch-area := TouchArea {
                mouse-cursor: pointer;
            }
            border-radius: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: SidebarState.is_open ? 5px : 0;
                animate spacing {
                    duration: 200ms;
                    easing: ease-in-out;
                }
                IconDisplay {
                    icon: IconSet.Package;
                    stroke: #8a8a8a55;
                    stroke-width: 2;
                    size: SidebarState.is_open ? 28px : 38px;
                    animate size {
                        duration: 100ms;
                        easing: ease-in-out;
                    }
                }
                Text {
                    text: "Mods";
                    font-size: 16px;
                    vertical-alignment: center;
                    color: #afafafaa;
                    font-weight: 600;
                    opacity: SidebarState.is_open ? 1 : 0;
                    animate opacity {
                        duration: 150ms;
                        easing: ease-in-out;
                    }
                }
            }
        }
    }

}