import { SidebarMenu as SidebarMenuState, SidebarState } from "../../state.slint";
import { IconDisplay, IconSet, Icon } from "@lucide";

export component SidebarMenu {
    in-out property <string> text: "?";
    in-out property <Icon> icon: IconSet.Package;
    in-out property <int> id;

    width: 100%;

    VerticalLayout {
        alignment: start;
        padding: SidebarState.is_open ? 15px : 11px;
        padding-top: SidebarState.is_open ? -10px : 0;
        animate padding {
            duration: 200ms;
            easing: ease-in-out;
        }
        animate padding-top {
            duration: 200ms;
            easing: ease-in-out;
        }
        Rectangle {
            padding: SidebarState.is_open ? 3px : 4px;
            background: (id == SidebarMenuState.selected)
                ? #2e2e2eaa
                : (touch-area.has-hover ? #2e2e2eaa : transparent);
            animate background {
                duration: 100ms;
            }
            animation-timer := Timer {
                interval: 100ms;
                running: false;

                triggered => {
                    SidebarMenuState.is_animating = false;
                }
            }
            touch-area := TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    SidebarMenuState.selected = id;
                }
            }
            border-radius: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: SidebarState.is_open ? 5px : 0;
                animate spacing {
                    duration: 200ms;
                    easing: ease-in-out;
                }
                IconDisplay {
                    icon: icon;
                    stroke: #8a8a8a55;
                    stroke-width: 2;
                    size: SidebarState.is_open ? 28px : 38px;
                    animate size {
                        duration: 100ms;
                        easing: ease-in-out;
                    }
                }
                Text {
                    text: text;
                    font-size: 16px;
                    vertical-alignment: center;
                    color: #afafafaa;
                    font-weight: 600;
                    opacity: SidebarState.is_open ? 1 : 0;
                    animate opacity {
                        duration: 150ms;
                        easing: ease-in-out;
                    }
                }
            }
        }
    }
}