import { SidebarMenu } from "SidebarMenu.slint";
import { IconSet } from "@lucide";

export component SidebarContainer {
    width: 100%;
    height: 100%;

    VerticalLayout {
    alignment: end;
        VerticalLayout {
            alignment: start;
            height: 90%;
            SidebarMenu {
                text: "Instances";
                icon: IconSet.Box;
                id: 0;
            }
            SidebarMenu {
                text: "Mods";
                icon: IconSet.Package;
                id: 1;
            }
            SidebarMenu {
                text: "Settings";
                icon: IconSet.Settings;
                id: 2;
            }
        }
    }
}