import { Sidebar } from "sidebar/Sidebar.slint";
import { MainMenu } from "menus/MainMenu.slint";
import { SidebarState } from "state.slint";
export { AccountMenuState } from "state.slint";
export { SidebarState } from "state.slint";

export component Window inherits Window {
    width: 1200px;
    height: 700px;
    background: #1e1e1e;
    title: "Ferris Launcher";

    HorizontalLayout {

        Sidebar {
            width: 60px;
        }

        MainMenu {
            width: 100%;
        }

    }

}
