import { SidebarMenu, SidebarState, InstanceData } from "../state.slint";
import { InstancesMenu } from "InstancesMenu.slint";

export component MainMenu {
    in-out property <int> columns: 4;
    in-out property <[InstanceData]> instances;
    width: 100%;
    height: 100%;

    Rectangle {

        width: 100%;
        height: 100%;

        InstancesMenu {
            x: SidebarState.is_open ? 165px : 30px;
            y: 15px;
            width: parent.width;
            height: parent.height - 30px;
            animate x {
                duration: 150ms;
                easing: ease-in-out;
            }
            visible: SidebarMenu.selected == 0;
            instances: root.instances;
        }

    }

}